AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
Metadata:
  
Mappings:
  
Conditions:
  
Resources:
  
  myCPUPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AutoScalingGroupName: EKLENECEK
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: !Ref EKLENECEK
  
  myAplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      SecurityGroups:
        - !GetAtt mySecurityGroup.GroupId
      Subnets: EKLENECEK

  
  myALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions: #required
        - Type: forward
          TargetGroupArn: !Ref myALBTargetGroup
      LoadBalancerArn: EKLENECEK
      Port: 80
      Protocol: HTTP
  
  myALBTarget Group:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 25
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: Integer
      Matcher:
        Matcher
      Name: String
      Port: Integer
      Protocol: String
      Tags:
        - Tag
      TargetGroupAttributes:
        - TargetGroupAttribute
      TargetType: String
      Targets:
        - TargetDescription
      UnhealthyThresholdCount: Integer
      VpcId: String
  
Transform:
  
Outputs: